### ISSUE TITLE
Stars not showing in Rails

### ISSUE THREAD

**Issue by codefeat** [wbotelhos/raty#196]
After following the steps to include raty in my app the stars or missing image default don't show
<img width="513" alt="screen shot 2016-11-23 at 7 17 02 am" src="https://cloud.githubusercontent.com/assets/5861334/20563466/64f35952-b14e-11e6-8fc0-59308b7a993c.png">
![image](https://cloud.githubusercontent.com/assets/5861334/20563481/73b5a15c-b14e-11e6-9a77-63d108dbf904.png)

**Comment by wbotelhos** [comment]
Hi,

I think you should do a separated `script` tag to import and another one to call the `raty`, inside `$(function() { // here })`.

**Comment by codefeat** [comment]
Hi,

Thanks for your response. I added separate script tags to import and call the raty inside the function. Still no luck. I also getting this error. My i'm running rails 5.0.0.1

<img width="551" alt="screen shot 2016-11-23 at 7 34 35 pm" src="https://cloud.githubusercontent.com/assets/5861334/20584013/479f823e-b1b4-11e6-8caf-eeaf7737fdfb.png">


<img width="543" alt="screen shot 2016-11-23 at 7 36 08 pm" src="https://cloud.githubusercontent.com/assets/5861334/20584007/3b4df6be-b1b4-11e6-9237-724e8e8c6281.png">

**Comment by wbotelhos** [comment]
Using Rails, you will need to import you assets from manifest (application.js). You should not set the local path `app/assets...`. You can check it going on your page source and clicking on link that will be broken. Try to look for: "Precompiling assets on Rails"

**Comment by jogaco** [comment]
Works fine for me on Rails and I'm doing it as @wbotelhos says, putting raty files under vendor/assets: 

And my application.js top lines look like this:
```
//= require jquery
//= require jquery_ujs
//= require_tree .
//= require_tree ../../../vendor/assets/javascripts
```

**Comment by arta** [comment]
@codefeat, it looks like you are following mackenziechild's video. You also missed the `data-score` attribute on your `.star-rating` div (see below).

If you put the `jquery.raty.js` in `app/assets/javascripts` folder (as mackenzie did) you do not need to edit `application.js`. The script will load, and precompile with all the other JS automatically because of its location. 

But, because `jquery.raty.js` is @wbotelhos script (as opposed to your own), it lives, by convention, in `vendor/assets/javascripts` folder. If you put it there, then to load and precompile it add this line to your `application.js`:

    //= require jquery.raty

Put the `star-half.png`, `star-off.png` and `star-on.png` to your `app/assets/images` folder. 

Instead of adding your jQ Raty customization code to your movies show page (as mackenzie does), add it where it by convention belongs, to your `reviews.coffee`:

    $( document ).on 'turbolinks:load', ->
      $( '.star-rating' ).raty
        path: '/assets',
        readOnly: true,
        score: ->
          $( this ).attr( 'data-score' )
      return

Indentation matters. 

Rails specific `$( document ).on 'turbolinks:load', -> ` replaces jQ "traditional" `$( document ).ready -> `. Swap them (after you get it working) and navigate to movies show pages to see why, or look at: http://stackoverflow.com/questions/18770517/rails-4-how-to-use-document-ready-with-turbo-links. Not doing it this way will also cause the stars to not show.

The `score: ...` key:value pair reads the value of the movie rating from the containing `.star-rating` div's attribute `data-score`; because that's where you supply it (via `review.rating`) by this code in your movies show page:

    <div class='star-rating' data-score=<%= review.rating %>></div>

Hope this helps.

**Comment by lauroengineer** [comment]
@arta how can you prevent from duplicating stars when moving back and forth on the browser using `$( document ).on 'turbolinks:load', ->`?

Im assuming its something like this, inside your controller.coffee? But im having a hard time fighting out the actions to prevent duplicating starts. 

Any thoughts? 

```
$(document).on 'ready page:load', ->
  # Actions to do
```

**Comment by arta** [comment]
@lauroengineer, to display Raty's stars at all, use: `$( document ).on 'turbolinks:load', ->` instead of: `$( document ).ready ->`. This allows Raty to display the stars but it may be the reason why extra "ghost" stars appear on browser back-tracing. To fix that issue, use Raty's own: `$( 'container' ).raty( 'reload' );` per @jakeland's https://github.com/wbotelhos/raty/issues/198#issuecomment-270380245. 

My review.coffee looks like this:

    # Read and convert numeric rating to Stars (on views/reviews/_review):
    $( document ).on 'turbolinks:load', ->
      $( '.star-rating' ).raty
        path: '/assets'
        readOnly: true
        score: ->
          $( this ).attr( 'data-score' )
      # reload to remove ghost stars on browser back tracing:
      $( '.star-rating' ).raty( 'reload' )

    # Read and convert numeric rating to Stars, set Star rating (on views/reviews/_form):
    $( document ).on 'turbolinks:load', ->
      $( '#star-rating' ).raty
        path: '/assets'
        scoreName: 'review[rating]'
        score: ->
          $( this ).attr( 'data-score' )
      $( '#star-rating' ).raty( 'reload' )

**Comment by wbotelhos** [comment]
I need to check the need of the method `reload`. Because this method just destroy and create again. Maybe it adds a extra `data` that prevents this. I'll check it soon. Thank you.

**Comment by mSafdarAli** [comment]
i had the same problem. After looking into it, i found out that you just need to include require_tree and require jquery.raty in application.js file.
It worked for me and hopefully will work for you too.

**Comment by minennick** [comment]
hey guys,
im getting an Uncaught TypeError: $(...).raty is not a function which hopefully is the reason for me the stars are not getting showed. But i dont know how to handle it.
What i've done so far:
Adding the images to app/assets/images
putting the jquery.raty.js into vendor/assets/javascripts
putting `//= require jquery.raty` into my application.js
and putting 
```
<script>
        $('.star-rating').raty({
          path: '/assets',
          readOnly: true,
          score: function() {
                return $(this).attr('data-score');
        }
      });
</script>
```
into my show.html.erb file

i also tried mckenziechilds tutorial which didnt work out for me.
with the coffee @arta is mentioning i dont get any errors but the stars are still not shown. 
i hope someone can help me out on this, thx

**Comment by wbotelhos** [comment]
Hi @minennick 

> $(...).raty is not a function

`raty` won't be a function if it is not imported. Check your Page Source and check if the path is right and check the Network section of Chrome to see if assets was loaded.

**Comment by minennick** [comment]
Hi @wbotelhos 
what do you mean by 

> Check your Page Source and check if the path is right

`path: '/assets',` in my script should be rigth. but i checked the Network section of Chrome and some assets are loaded but jquery.raty.js is **not**. So the question is why? 
I tried a few different things:
putting jquery.raty.js back to app/assets/javascripts
and tried precompiling in config/initializers/assets.rb

**Comment by wbotelhos** [comment]
@minennick 

If you are using Rails, your path should com from a `image_url`, since we need to now the name of the asset plus the MD5 value like: `/assets/icons/start-on-123md5here.svg`.

You need some think like:

```
starEmptyOff: '<%= image_path 'vendor/raty/star-empty-off.svg' %>',
starHalf:     '<%= image_path 'vendor/raty/star-half.svg' %>',
starOff:      '<%= image_path 'vendor/raty/star-off.svg' %>',
starOn:       '<%= image_path 'vendor/raty/star-on.svg' %>'
```

- You assets into `app/assets/images` / `app/assets/javascripts` / `app/assets/stylesheets`.
- Everythig imported with the right path.

For more doubt I recomend to use the StackOverflow, since we used to use Issues for bugs. (:
